// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: getWords.sql

package database

import (
	"context"
)

const getWords = `-- name: GetWords :many
SELECT id, first, second, third from wordoftheminutes
`

func (q *Queries) GetWords(ctx context.Context) ([]Wordoftheminute, error) {
	rows, err := q.db.QueryContext(ctx, getWords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wordoftheminute
	for rows.Next() {
		var i Wordoftheminute
		if err := rows.Scan(
			&i.ID,
			&i.First,
			&i.Second,
			&i.Third,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
