// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: insertWord.sql

package database

import (
	"context"
	"database/sql"
)

const insertWord = `-- name: InsertWord :one
INSERT INTO wordoftheminutes (id, first, second, third)
VALUES ($1, $2, $3, $4)
RETURNING id, first, second, third
`

type InsertWordParams struct {
	ID     string
	First  sql.NullString
	Second sql.NullString
	Third  sql.NullString
}

func (q *Queries) InsertWord(ctx context.Context, arg InsertWordParams) (Wordoftheminute, error) {
	row := q.db.QueryRowContext(ctx, insertWord,
		arg.ID,
		arg.First,
		arg.Second,
		arg.Third,
	)
	var i Wordoftheminute
	err := row.Scan(
		&i.ID,
		&i.First,
		&i.Second,
		&i.Third,
	)
	return i, err
}
