// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Wordoftheminute struct {
	ID     string
	First  sql.NullString
	Second sql.NullString
	Third  sql.NullString
}
