services:
    app: 
        build: 
            context: .
        container_name: wotm
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - redis
        networks:
            - app-network

    redis:
        image: redis:latest
        container_name: redis
        volumes:
            - redis-data:/data
        networks:
            - app-network

volumes:
    redis-data:

networks:
    app-network:
        driver: bridge